apiVersion: v2
name: openstack-management-api
description: Resource Management API for OpenStack Environments
type: application
version: 0.0.1-alpha
appVersion: "0.0.1-alpha"
maintainers:
  - name: Dennis Pfisterer
    email: dennis.pfisterer@dhbw.de
