apiVersion: v2
name: openstack-management-api
description: Resource Management API for OpenStack Environments
type: application
version: 0.8.12-test.2
appVersion: "0.8.12-test.2"
maintainers:
  - name: Dennis Pfisterer
    email: dennis.pfisterer@dhbw.de
