{{- $comp := dict "context" . "component" "openstack-management" -}}
{{- $name := include "openstack-mangament-api.componentName" $comp -}}
{{- $labels := include "openstack-mangament-api.labels" $comp -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  db-connection-string: {{ .Values.openstackManagementApi.db.connectionString | quote }}
  openstack-application-credential-secret: {{ .Values.openstackManagementApi.openstack.applicationCredentialSecret | quote }}
